// GTA IV vehicles: {model name, display name, class}. Base-game names from the
// GTA Connected vehicle model list (wiki.gtaconnected.com/Resources/GTAIV/VehicleModels);
// EFLC (TLAD / TBoGT) models are listed too and, like every entry, are dropped
// at menu build when IS_MODEL_IN_CDIMAGE says the installed game lacks them.
static const char *CLASS_NAMES[] = {
    "Sedans & coupes", "Sports", "Muscle & classics", "SUVs, vans & pickups", "Trucks & service",
    "Emergency", "Motorcycles", "Boats", "Helicopters", "The Lost and Damned", "The Ballad of Gay Tony",
};
#define CLASS_COUNT ((int)(sizeof(CLASS_NAMES) / sizeof(CLASS_NAMES[0])))
static const struct { const char *model; const char *name; unsigned char cls; } IV_VEHICLES[] = {
    { "admiral",     "Admiral",               0 },
    { "blista",      "Blista Compact",        0 },
    { "chavos",      "Chavos",                0 },
    { "cognoscenti", "Cognoscenti",           0 },
    { "df8",         "DF8-90",                0 },
    { "dilettante",  "Dilettante",            0 },
    { "e109",        "E109",                  0 },
    { "emperor",     "Emperor",               0 },
    { "emperor2",    "Emperor (rusty)",       0 },
    { "esperanto",   "Esperanto",             0 },
    { "feroci",      "Feroci",                0 },
    { "feroci2",     "Feroci (FlyUS)",        0 },
    { "fortune",     "Fortune",               0 },
    { "futo",        "Futo",                  0 },
    { "hakumai",     "Hakumai",               0 },
    { "ingot",       "Ingot",                 0 },
    { "intruder",    "Intruder",              0 },
    { "lokus",       "Lokus",                 0 },
    { "marbella",    "Marbelle",              0 },
    { "merit",       "Merit",                 0 },
    { "oracle",      "Oracle",                0 },
    { "pinnacle",    "Pinnacle",              0 },
    { "pmp600",      "PMP 600",               0 },
    { "premier",     "Premier",               0 },
    { "pres",        "Presidente",            0 },
    { "primo",       "Primo",                 0 },
    { "schafter",    "Schafter",              0 },
    { "sentinel",    "Sentinel",              0 },
    { "solair",      "Solair",                0 },
    { "stratum",     "Stratum",               0 },
    { "stretch",     "Stretch",               0 },
    { "sultan",      "Sultan",                0 },
    { "uranus",      "Uranus",                0 },
    { "vincent",     "Vincent",               0 },
    { "washington",  "Washington",            0 },
    { "willard",     "Willard",               0 },
    { "banshee",     "Banshee",               1 },
    { "comet",       "Comet",                 1 },
    { "coquette",    "Coquette",              1 },
    { "feltzer",     "Feltzer",               1 },
    { "infernus",    "Infernus",              1 },
    { "sultanrs",    "Sultan RS",             1 },
    { "supergt",     "Super GT",              1 },
    { "turismo",     "Turismo",               1 },
    { "buccaneer",   "Buccaneer",             2 },
    { "dukes",       "Dukes",                 2 },
    { "faction",     "Faction",               2 },
    { "manana",      "Manana",                2 },
    { "peyote",      "Peyote",                2 },
    { "ruiner",      "Ruiner",                2 },
    { "sabre",       "Sabre",                 2 },
    { "sabre2",      "Sabre (beater)",        2 },
    { "sabregt",     "Sabre GT",              2 },
    { "stalion",     "Stallion",              2 },
    { "vigero",      "Vigero",                2 },
    { "vigero2",     "Vigero (rusty)",        2 },
    { "virgo",       "Virgo",                 2 },
    { "voodoo",      "Voodoo",                2 },
    { "bobcat",      "Bobcat",                3 },
    { "burrito",     "Burrito",               3 },
    { "burrito2",    "Burrito (Rockstar)",    3 },
    { "cavalcade",   "Cavalcade",             3 },
    { "habanero",    "Habanero",              3 },
    { "huntley",     "Huntley Sport",         3 },
    { "landstalker", "Landstalker",           3 },
    { "minivan",     "Minivan",               3 },
    { "moonbeam",    "Moonbeam",              3 },
    { "patriot",     "Patriot",               3 },
    { "perennial",   "Perennial",             3 },
    { "perennial2",  "Perennial (FlyUS)",     3 },
    { "pony",        "Pony",                  3 },
    { "rancher",     "Rancher",               3 },
    { "rebla",       "Rebla",                 3 },
    { "speedo",      "Speedo",                3 },
    { "steed",       "Steed",                 3 },
    { "airtug",      "Airtug",                4 },
    { "benson",      "Benson",                4 },
    { "biff",        "Biff",                  4 },
    { "boxville",    "Boxville",              4 },
    { "bus",         "Bus",                   4 },
    { "cabby",       "Cabby",                 4 },
    { "flatbed",     "Flatbed",               4 },
    { "forklift",    "Forklift",              4 },
    { "mrtasty",     "Mr. Tasty",             4 },
    { "mule",        "Mule",                  4 },
    { "packer",      "Packer",                4 },
    { "phantom",     "Phantom",               4 },
    { "ripley",      "Ripley",                4 },
    { "rom",         "Roman's Taxi",          4 },
    { "stockade",    "Securicar",             4 },
    { "taxi",        "Taxi",                  4 },
    { "taxi2",       "Taxi (Merit)",          4 },
    { "trash",       "Trashmaster",           4 },
    { "yankee",      "Yankee",                4 },
    { "ambulance",   "Ambulance",             5 },
    { "fbi",         "FIB Buffalo",           5 },
    { "firetruk",    "Fire Truck",            5 },
    { "noose",       "NOOSE Patrol Car",      5 },
    { "nstockade",   "NOOSE Stockade",        5 },
    { "police",      "Police Cruiser",        5 },
    { "police2",     "Police Patrol",         5 },
    { "polpatriot",  "Police Patriot",        5 },
    { "pstockade",   "Police Stockade",       5 },
    { "bobber",      "Bobber",                6 },
    { "faggio",      "Faggio",                6 },
    { "hellfury",    "Hellfury",              6 },
    { "nrg900",      "NRG 900",               6 },
    { "pcj",         "PCJ 600",               6 },
    { "sanchez",     "Sanchez",               6 },
    { "zombieb",     "Zombie",                6 },
    { "dinghy",      "Dinghy",                7 },
    { "jetmax",      "Jetmax",                7 },
    { "marquis",     "Marquis",               7 },
    { "predator",    "Predator",              7 },
    { "reefer",      "Reefer",                7 },
    { "squalo",      "Squalo",                7 },
    { "tropic",      "Tropic",                7 },
    { "tuga",        "Tug",                   7 },
    { "annihilator", "Annihilator",           8 },
    { "maverick",    "Maverick",              8 },
    { "polmav",      "Police Maverick",       8 },
    { "tourmav",     "Tour Maverick",         8 },
    // TLAD
    { "angel",       "Angel",                 9 },
    { "bati",        "Bati 800",              9 },
    { "bati2",       "Bati Custom",           9 },
    { "daemon",      "Daemon",                9 },
    { "diabolus",    "Diabolus",              9 },
    { "double",      "Double T",              9 },
    { "hakuchou",    "Hakuchou",              9 },
    { "hexer",       "Hexer",                 9 },
    { "innovation",  "Innovation",            9 },
    { "lycan",       "Lycan",                 9 },
    { "nightblade",  "Nightblade",            9 },
    { "revenant",    "Revenant",              9 },
    { "wayfarer",    "Wayfarer",              9 },
    { "wolfsbane",   "Wolfsbane",             9 },
    { "gburrito",    "Gang Burrito",          9 },
    { "slamvan",     "Slamvan",               9 },
    { "regina",      "Regina",                9 },
    { "rhapsody",    "Rhapsody",              9 },
    { "towtruck",    "Tow Truck",             9 },
    { "prbus",       "Prison Bus",            9 },
    // TBoGT
    { "akuma",       "Akuma",                 10 },
    { "vader",       "Vader",                 10 },
    { "faggio2",     "Faggio (retro)",        10 },
    { "bulletgt",    "Bullet GT",             10 },
    { "f620",        "F620",                  10 },
    { "serrano",     "Serrano",               10 },
    { "schafter2",   "Schafter (TBoGT)",      10 },
    { "stretche",    "Stretch E",             10 },
    { "superd",      "Super Diamond",         10 },
    { "superd2",     "Super Drop Diamond",    10 },
    { "tampa",       "Tampa",                 10 },
    { "buffalo",     "Buffalo",               10 },
    { "police3",     "Police Cruiser (Buffalo)", 10 },
    { "police4",     "Police Stinger",        10 },
    { "policeb",     "Police Bike",           10 },
    { "apc",         "APC",                   10 },
    { "buzzard",     "Buzzard",               10 },
    { "swift",       "Swift",                 10 },
    { "skylift",     "Skylift",               10 },
    { "blade",       "Blade",                 10 },
    { "floater",     "Floater",               10 },
    { "smuggler",    "Smuggler",              10 },
    { "caddy",       "Caddy",                 10 },
    { "brickade",    "Brickade",              10 },
};
#define VEHICLE_COUNT ((int)(sizeof(IV_VEHICLES) / sizeof(IV_VEHICLES[0])))

// vehicle spawn cheats: {display name, phone number, model}. IV numbers from the
// game; TLAD / TBoGT ones are hidden when the model is not installed.
static const struct { const char *name; const char *number; const char *model; } SPAWN_CHEATS[] = {
    { "Annihilator",      "359-555-0100", "annihilator" },
    { "Cognoscenti",      "227-555-0142", "cognoscenti" },
    { "Comet",            "227-555-0175", "comet" },
    { "FIB Buffalo",      "227-555-0100", "fbi" },
    { "Jetmax",           "938-555-0100", "jetmax" },
    { "NRG 900",          "625-555-0100", "nrg900" },
    { "Sanchez",          "625-555-0150", "sanchez" },
    { "Super GT",         "227-555-0168", "supergt" },
    { "Turismo",          "227-555-0147", "turismo" },
    { "Innovation (TLAD)",      "245-555-0100", "innovation" },
    { "Hexer (TLAD)",           "245-555-0150", "hexer" },
    { "Double T (TLAD)",        "245-555-0125", "double" },
    { "Hakuchou (TLAD)",        "245-555-0199", "hakuchou" },
    { "Gang Burrito (TLAD)",    "826-555-0150", "gburrito" },
    { "Slamvan (TLAD)",         "826-555-0100", "slamvan" },
    { "APC (TBoGT)",            "272-555-8265", "apc" },
    { "Buzzard (TBoGT)",        "359-555-2899", "buzzard" },
    { "Bullet GT (TBoGT)",      "227-555-9666", "bulletgt" },
    { "Akuma (TBoGT)",          "625-555-0200", "akuma" },
    { "Vader (TBoGT)",          "625-555-3273", "vader" },
    { "Floater (TBoGT)",        "938-555-0150", "floater" },
};
#define SPAWN_CHEAT_COUNT ((int)(sizeof(SPAWN_CHEATS) / sizeof(SPAWN_CHEATS[0])))
